refactor: exit codes & duplicate code

diff --git a/ms-bkp b/ms-bkp
--- a/ms-bkp
+++ b/ms-bkp
@@ -6,6 +6,7 @@
 # ms-bkp script version.
 VERSION="1.0.0"
 
+# TODO not required this once config options are complete.
 if [ -f .env ]; then
 	export $(echo $(cat .env | sed 's/#.*//g' | xargs) | envsubst)
 fi
@@ -25,7 +26,7 @@ MYSQL_LOGIN="-u $MYSQL_USER -h $MYSQL_HOST"
 
 # Function to display error/help messages.
 function show_msg() {
-	[[ $1 == "invalid" ]] && echo -e "Invalid option"
+	[[ $1 == "invalid" ]] && echo "Invalid option" && exit 1
 	[[ $1 == "help" ]] && echo "Usage:
 ms-bkp [option]
 Backup all mysql tables as separate compressed files.
@@ -36,7 +37,6 @@ Options:
 	-i,  --include-db           remove database from ignore backup list
 	-h,  --help                 display help and exit
 	-v,  --version              display ms-bkp script version"
-	exit 1
 }
 
 # Function to export databases.
@@ -48,7 +48,7 @@ function export_db() {
 	# Check backup path and create it if necessary
 	DBS="$($MYSQL $MYSQL_LOGIN -Bse 'show databases')"
 
-	# Create path if it doesn't exist
+	# Create path yif it doesn't exist
 	[ ! -d $BACKUP_PATH ] && mkdir -p $BACKUP_PATH || echo -e "$BACKUP_PATH exist \n"
 
 	# Change permissions so anyone can access backups
@@ -78,17 +78,17 @@ function open_bkp_dir() {
 	echo
 	if [[ $REPLY =~ ^[Yy]$ ]]; then
 		if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-			nautilus $BKP_PATH > /dev/null
+			nautilus $BKP_PATH & > /dev/null
 		elif [[ "$OSTYPE" == "darwin"* ]]; then
 			open $BKP_PATH > /dev/null
 		fi
 	fi
-	exit 1
+	exit 0
 }
 
 # Check input value.
 if [ $# -gt 1 ]; then
-	echo -e "Too many arguments:- $*"
+	echo "Too many arguments:- $*"
 	exit 1
 else
 	# Check input and show messages as per options.
@@ -96,19 +96,14 @@ else
 		show_msg help
 	elif [[ ($* == "--version") || ($* == "-v") ]]; then
 		echo -e "ms-bkp v${VERSION} \nVisit :- https://vinugawade.github.io/ms-bkp"
-		exit 1
 	elif [[ ($* == "--configs") || ($* == "-c") ]]; then
 		echo -e "ms-bkp show all configs"
-		exit 1
 	elif [[ ($* == "--set-config") || ($* == "-sc") ]]; then
 		echo -e "ms-bkp init config"
-		exit 1
 	elif [[ ($* == "--exclude-db") || ($* == "-e") ]]; then
 		echo -e "ms-bkp add DB in ignore list"
-		exit 1
 	elif [[ ($* == "--include-db") || ($* == "-i") ]]; then
 		echo -e "ms-bkp remove DB from ignore list"
-		exit 1
 	else
 		# If the script is being run with no arguments. If it is,
 		# it will run the `export_db` and then the `open_bkp_dir` function.
@@ -119,6 +114,5 @@ else
 			show_msg invalid
 		fi
 	fi
+	exit 0
 fi
-
-exit 0
